### PR TITLE
librespot: PIL workaround

### PR DESCRIPTION
**Pull request by henri-funck**
Hello,
Commit #8536 fixes importing PIL, but Librespot still fails creating 16x9 fanarts.
This pull request allows Librespot to play, and leaves me time to find a more appropriate solution.
I expect to be able to work on this the week after next.

### CODE REVIEW

**Comment by heitbaum** [comment]
> Hello, Commit #8536 fixes importing PIL, but Librespot still fails creating 16x9 fanarts. This pull request allows Librespot to play, and leaves me time to find a more appropriate solution. I expect to be able to work on this the week after next.

Can you share the error that you are getting? Usual questions: Is this a new issue with librespot? Is it a compatibility between librespot and Pillow 10.2.0? Did it work with Pillow 10.1.0. Do Pillow or librespot know about the issue? How do you reproduce the issue? …

good that the erroring code is identified, and fine for self builders, but going to put this PR on hold until an upstream(able)/upstream fix.

**Comment by heitbaum** [comment]
I’m assuming the error lies between 

https://github.com/LibreELEC/LibreELEC.tv/blob/96b4665e4bb8bc16d09bc1d0f1fa7cdd2eeee944/packages/addons/service/librespot/source/resources/lib/service.py#L40-L46

**Comment by henri-funck** [comment]
The problem occurs at line 46 (AttributeError: 'JpegImageFile' object has no attribute 'new').
The get_fanart method converts a square cover art into 16x9 format and caches the result.
The conversion is purely esthetic and allows displaying the whole of the cover art in Kodi rather than only a portion of it.
The code assumes that this always works and the error breaks the python service.
Otherwise librespot and python script are running fine.

**Comment by antonlacon** [comment]
Does this work for better error handling then? https://github.com/antonlacon/LibreELEC.tv/commit/0820c884f9b45cd4df74ca64a0ba196f1b852a89 Untested; I don't use the addon.

**Comment by henri-funck** [comment]
Thank you @antonlacon, but your suggestion and the bypass of this pull request are equivalent because PIL.Image.new systematically fails

**Comment by vpeter4** [comment]
@henri-funck: Can you make one small standalone python sample with this code https://github.com/LibreELEC/LibreELEC.tv/blob/96b4665e4bb8bc16d09bc1d0f1fa7cdd2eeee944/packages/addons/service/librespot/source/resources/lib/service.py#L40-L46 and run it directly in python? I tried and at least works on x86 device but you are using RPi right?

**Comment by henri-funck** [comment]
The code below works from the console @vpeter4
It fails from Kodi with `Librespot: 'JpegImageFile' object has no attribute 'new'`
Could it lie with how Kodi imports PIL?
```
import os
import PIL.Image
import urllib.request

_FANART_DIR='/storage/downloads/work'


def get_fanart(url, max_fanarts):
    name = os.path.basename(url)
    target = os.path.join(_FANART_DIR, f'{name}_16x9')
    if not os.path.exists(target):
        if not os.path.exists(_FANART_DIR):
            os.makedirs(_FANART_DIR)
        files = os.listdir(_FANART_DIR)
        files = [os.path.join(_FANART_DIR, file) for file in files if os.path.isfile(
            os.path.join(_FANART_DIR, file))]
        files.sort(key=os.path.getmtime)
        for file in files[:-max_fanarts]:
            os.remove(file)
        source = os.path.join(_FANART_DIR, f'{name}_9x9')
        urllib.request.urlretrieve(url, source)
        image = PIL.Image.open(source)
        width, height = image.size
        new_width = int(height * 16 / 9)
        delta_w = new_width - width
        new_image = PIL.Image.new('RGB', (new_width, height), (0, 0, 0))
        new_image.paste(image, (delta_w // 2, 0))
        new_image.save(target, 'JPEG', optimize=True)
        os.remove(source)
    return target


get_fanart("https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228", 2)
```

**Comment by vpeter4** [comment]
I have put your code above into one kodi addon and still works on x86 generic legacy.
Will try on some arm device later today.

**Comment by henri-funck** [comment]
Thank you for your help @vpeter4
The only script.module.pil on my system is the stub shipped with LibreELEC.
Last time I tried Librespot worked fine on LibreELEC 11 for RPi4 (arm).
Librespot fails at least on my LibreELEC nightly-20240120-96b4665 for RPi5 (aarch64).
I will try Librespot on a fresh LibreELEC nightly for RPi4 (aarch64) and report here. It should be the same as on RPi5, right?
```
more /storage/.kodi/temp/kodi.log | grep script.module.pil
2023-12-24 10:01:05.905 T:1428     info <general>: CAddonMgr::FindAddons: script.module.pil v5.1.0 installed

ls /storage/.kodi/addons/script.module.pil
ls: /storage/.kodi/addons/script.module.pil: No such file or directory

ls -alR /usr/share/kodi/addons/script.module.pil/
/usr/share/kodi/addons/script.module.pil/:
total 8
drwxr-xr-x    2 root     root            48 Jan 20 11:58 .
drwxr-xr-x   58 root     root          1937 Jan 20 11:59 ..
-rw-r--r--    1 root     root           476 Jan 14 17:45 addon.xml
-rw-r--r--    1 root     root          7237 Jan 14 17:45 icon.png

more /usr/share/kodi/addons/script.module.pil/addon.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<addon id="script.module.pil"
       name="Python Image Library"
       version="5.1.0"
       provider-name="PythonWare">
  <requires>
    <import addon="xbmc.python" version="3.0.0"/>
  </requires>
  <extension point="xbmc.python.module"
             library="lib" />
  <extension point="xbmc.addon.metadata">
    <platform>all</platform>
    <assets>
      <icon>icon.png</icon>
    </assets>
  </extension>
</addon>
```

**Comment by vpeter4** [comment]
It looks all the same on `LibreELEC-Generic-legacy.x86_64-12.0-nightly-20240120-96b4665.img.gz`.
The only difference is that sample code does work. No idea why it doesn't on RPi. I don't own any to do test myself.

**Comment by henri-funck** [comment]
Librespot works fine on LibreELEC-RPi4.aarch64-12.0-nightly-20240123-74d677a.
My RPi5 install must be buggy.
Thank you for your patience and #8536.
Closing.

**Comment by bdgra** [comment]
@henri-funck does this also work for version 20.0.130? I tried it but unfortunately without luck. The version 20.0.130 works perfect. Only the artwork looks like it has been zoomed in.
