### PR TITLE
u-boot: fix build openssl-related build errors

### PR DESCRIPTION
**Pull request by HiassofT**
mkimage and several other tools now require openssl on the host.

Add the missing dependencies and host compiler/linker options so openssl from the toolchain is properly picked up and used.

only build-tested for AW A64 - some more build+runtime tests would be great

### CODE REVIEW

**Comment by heitbaum** [comment]
I tested these 2 commits with #5738 to see if it would fix my iMX8 u-boot error (it didn’t). 

with or without the 2 patches - my builds were the same - in that - apart from the iMX8 error - all completed.

My apt is below.
```
$ apt list --installed | grep ssl

libio-socket-ssl-perl/bionic-updates,bionic-security,now 2.060-3~ubuntu18.04.1 all [installed]
libnet-smtp-ssl-perl/bionic,now 1.04-1 all [installed]
libnet-ssleay-perl/bionic-updates,bionic-security,now 1.84-1ubuntu0.2 amd64 [installed]
libssl-dev/now 1.1.1-1ubuntu2.1~18.04.9 amd64 [installed,upgradable to: 1.1.1-1ubuntu2.1~18.04.13]
libssl1.0.0/now 1.0.2n-1ubuntu5.6 amd64 [installed,upgradable to: 1.0.2n-1ubuntu5.7]
libssl1.1/now 1.1.1-1ubuntu2.1~18.04.9 amd64 [installed,upgradable to: 1.1.1-1ubuntu2.1~18.04.13]
openssl/now 1.1.1-1ubuntu2.1~18.04.9 amd64 [installed,upgradable to: 1.1.1-1ubuntu2.1~18.04.13]
perl-openssl-defaults/bionic,now 3build1 amd64 [installed]
```

**Comment by jernejsk** [comment]
This MR fixes only building tools (host toolchain). Can you show your build log for imx8?

**Comment by heitbaum** [comment]
> This MR fixes only building tools (host toolchain). Can you show your build log for imx8?

here is the error 

`$ PROJECT=NXP ARCH=arm DEVICE=iMX8 make image`

http://paste.ubuntu.com/p/YS4chkH3Qp/

```
arch/arm/dts/imx8mq-evk.dtb size: 
stat: cannot stat 'arch/arm/dts/imx8mq-evk.dtb': No such file or directory
  DTC     arch/arm/dts/imx8mp-evk.dtb
  DTC     arch/arm/dts/imx8mp-phyboard-pollux-rdk.dtb
  DTC     arch/arm/dts/imx8mq-pico-pi.dtb
  SHIPPED dts/dt.dtb
  MKIMAGE u-boot.itb
u-boot.itb.tmp: Warning (unit_address_vs_reg): /images/uboot@1: node has a unit name, but no reg property
u-boot.itb.tmp: Warning (unit_address_vs_reg): /images/fdt@1: node has a unit name, but no reg property
u-boot.itb.tmp: Warning (unit_address_vs_reg): /images/atf@1: node has a unit name, but no reg property
u-boot.itb.tmp: Warning (unit_address_vs_reg): /configurations/config@1: node has a unit name, but no reg property
./tools/mkimage: verify_header failed for FIT Image support with exit code 1
make[1]: *** [Makefile:1442: u-boot.itb] Error 1
make[1]: *** Deleting file 'u-boot.itb'
make[1]: *** Waiting for unfinished jobs....
```

**Comment by jernejsk** [comment]
BTW, paste is not public. Please make it or move it to other paste service.

This has nothing to do with openssl. For some reason U-Boot doesn't find arch/arm/dts/imx8mq-evk.dtb. There are several possible reasons for that like missing config option, missing dts file, typo/missing line in Makefile.

**Comment by heitbaum** [comment]
It is strange. 2021.07 works with kernel 5.15, but not 2021.10. But both 2021.10 and 2021.07 work with 5.14. So haven’t got to the bottom of it. It was a cross fingers and hope approach - lol -

also updated the pastebin URL.

**Comment by HiassofT** [comment]
@heitbaum you don't need libssl-dev on host, better remove that. If it's installed you won't notice LE packages picking up openssl from host instead from toolchain (like u-boot did before this PR)

**Comment by jernejsk** [comment]
@5schatten Can you try this PR? I would, but my distro doesn't have a notion of dev packages, headers are installed together with lib.

**Comment by heitbaum** [comment]
I have removed libssl-dev and got the following error.
```
In file included from tools/aisimage.c:9:0:
include/image.h:1178:12: fatal error: openssl/evp.h: No such file or directory
 #  include <openssl/evp.h>
            ^~~~~~~~~~~~~~~
compilation terminated.
```
With the 2 commits. It builds correctly. So the PR is good for me on 18.04

**Review by heitbaum — APPROVED** [review]

**Review by CvH — APPROVED** [review]
