### PR TITLE
linux (default, RPi): fix perf build with glibc 2.30

### PR DESCRIPTION
**Pull request by HiassofT**
perf build fails because glibc 2.30 includes a gettid() function:

```
jvmti/jvmti_agent.c:48:21: error: static declaration of 'gettid' follows non-static declaration
   48 | static inline pid_t gettid(void)
      |                     ^~~~~~
In file included from /home/hias/rpi/libreelec-master/build.LibreELEC-RPi4.arm-9.80-devel/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/unistd.h:1170,
                 from jvmti/jvmti_agent.c:33:
/home/hias/rpi/libreelec-master/build.LibreELEC-RPi4.arm-9.80-devel/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/bits/unistd_ext.h:34:16: note: previous declaration of 'gettid' was here
   34 | extern __pid_t gettid (void) __THROW;
      |                ^~~~~~
```

This has already been fixed in the 5.3 kernel tree. Add a backport
commit until the fix dribbles down into stable 5.2 or we swtich to 5.3.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Thanks, although I never saw this issue on Ubuntu 16.04 or 17.10 - weird!

**Comment by MilhouseVH** [comment]
A but more explanation from Slack:
"
got it here on Debian Stretch with openjdk 8 (jdk, not jre) installed. according to kernel discussion it probably depends on if you have jdk or jre installed https://lkml.org/lkml/2019/6/12/1258
"

(I appear to have jre installed)
