### PR TITLE
dvblast: fix build with aml-3.14

### PR DESCRIPTION
**Pull request by lrusak**
I'm unable to figure out this error

```
dvb.c:639:30: error: unknown type name 'fe_caps_t'
 static fe_code_rate_t GetFEC(fe_caps_t fe_caps, int i_fec_value)
```

### CODE REVIEW

**Comment by stefansaraev** [comment]
here a fix https://github.com/stefansaraev/TB/commit/b40971fadb34f715ced0886d0a10dd114b8396bb

**Comment by lrusak** [comment]
Thanks @stefansaraev you're my hero
