### PR TITLE
linux (Generic): update to linux-5.6

### PR DESCRIPTION
**Pull request by MilhouseVH**
~xf86-video-nvidia-legacy is building, but currently broken.~

~xf86-video-nvidia is building, may or may not be broken.~

----

#### Test build posts
| Kernel | Generic | Announce |
| :--- | :---: | :----: |
| 5.6-rc1 | [`#0212x`](https://forum.kodi.tv/showthread.php?tid=343069&pid=2923861#pid2923861) | [Link](https://lkml.org/lkml/2020/2/9/221) |
| 5.6-rc2 | [`#0217x`](https://forum.kodi.tv/showthread.php?tid=343069&pid=2925150#pid2925150) | [Link](https://lkml.org/lkml/2020/2/17/967) |
| 5.6-rc3 | [`#0225x`](https://forum.kodi.tv/showthread.php?tid=343069&pid=2927326#pid2927326) | [Link](https://lkml.org/lkml/2020/2/23/336) |
| 5.6-rc4 |[`#0302x`](https://forum.kodi.tv/showthread.php?tid=343069&pid=2928670#pid2928670) | [Link](https://lkml.org/lkml/2020/3/1/338) |
| 5.6-rc5 | [`#0309x`](https://forum.kodi.tv/showthread.php?tid=343069&pid=2930455#pid2930455) | [Link](https://lkml.org/lkml/2020/3/8/398) |
| 5.6-rc6 | [`#0315x`](https://forum.kodi.tv/showthread.php?tid=343069&pid=2931838#pid2931838) | [Link](https://lkml.org/lkml/2020/3/15/312) |
| 5.6-rc7 | [`#0324x`](https://forum.kodi.tv/showthread.php?tid=343069&pid=2934146#pid2934146) | [Link](https://lkml.org/lkml/2020/3/22/419) |

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Latest amdgpu firmware for vega10/12/20.

**Comment by MilhouseVH** [comment]
5.6-rc7 still builds fine with current LE master, but 5.6 final fails: http://ix.io/2fXQ
```
/home/neil/projects/scratch/alternates/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.80-devel-next/build/wireguard-linux-compat-v0.0.20200215/src/queueing.h:100:2: error: implicit declaration of function 'skb_reset_tc'; did you mean 'nf_reset_ct'? [-Werror=implicit-function-declaration]
  100 |  skb_reset_tc(skb);
      |  ^~~~~~~~~~~~
      |  nf_reset_ct
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:267: /home/neil/projects/scratch/alternates/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.80-devel-next/build/wireguard-linux-compat-v0.0.20200215/src/main.o] Error 1
```

This is due to a last minute change in 5.6: https://github.com/torvalds/linux/commit/2c64605b590edadb3fb46d1ec6badb49e940b479

I've bumped `wireguard-linux-compat` and added a temporary patch workaround for the build issue from upstream. Not yet build tested.

**Comment by MilhouseVH** [comment]
wireguard-linux-compat v1.0.20200330 is released, so bump to that version.
